dataset: "LibriTTS"
lang_id: 0

root:
  corpus_path: "/home/r06942045/myData/LibriTTS"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/LibriTTS"
  preprocessed_path: "./preprocessed_data/LibriTTS"

path:
  child_path: "train-all"
  preprocessed_path: "./preprocessed_data/LibriTTS/train-all"

subsets:
  #train: "train-all"
  #train: "train-clean"
  train:
    - train-clean-100
    - train-clean-360
    - train-other-500
  val: []
  test: []

