# python main_cli.py fit -c cli_config/xvec/fit.yaml

seed_everything: 42

model:
  class_path: lightning.systems.xvec.XvecFitSystem
  init_args:
    p_dropout: 0.0

    optim_config:
      class_path: torch.optim.Adam
      init_args:
        lr: 5e-4

    lr_sched_config:
      class_path: torch.optim.lr_scheduler.OneCycleLR
      init_args:
        max_lr: 2e-3
        cycle_momentum: False
        div_factor: 5
        final_div_factor: 1e+3
        pct_start: 0.15

data: cli_config/xvec/data.yaml

trainer:
  ### Train settings
  max_epochs: 200
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1

  ### Logging and saving settings
  enable_checkpointing: True
  default_root_dir: output/xvec

  ### GPU-related settings
  accelerator: gpu
  devices: [0]
  strategy: ddp
  auto_select_gpus: True

  ### Callbacks
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        log_momentum: True

  ### Malicious settings
  profiler: simple

  ### Depreciated settings
  # deterministic: True

