  class_path: lightning.systems.XvecFitSystem
  init_args:
    model:
      class_path: lightning.model.XvecTDNN
      init_args:
        p_dropout: 0.5

    optim_config:
      class_path: torch.optim.Adam
      init_args:
        lr: 5e-4

    lr_sched_config:
      class_path: torch.optim.lr_scheduler.OneCycleLR
      init_args:
        max_lr: 2e-3
        cycle_momentum: False
        div_factor: 5
        final_div_factor: 1e+3
        pct_start: 0.15

