dataset: "LibriTTS_VCTK"
lang_id: 0

root:
  corpus_path: "/home/r06942045/myData"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data"
  preprocessed_path: "./preprocessed_data"

path:
  child_path: "LibriTTS_VCTK"
  corpus_path: "/home/r06942045/myData"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data"
  preprocessed_path: "./preprocessed_data/LibriTTS_VCTK"

subsets:
  train:
    - LibriTTS/train-all
  transfer:
    - VCTK/American
    - VCTK/Canadian
    - VCTK/English
    - VCTK/Irish
    - VCTK/Scottish
    - VCTK/SouthAfrican
  val:
    - VCTK/Indian
    - VCTK/British
    - VCTK/NewZealand
    - LibriTTS/dev-clean
  test:
    - LibriTTS/test-clean
    - VCTK/AustralianEnglish
    - VCTK/NorthernIrish
    - VCTK/Welsh

preprocessing:
  val_size: 512
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: Null # set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: False
    log: True # don't use with normalization
    word: False  # word-level average
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
    log: False # don't use with normalization
    word: False  # word-level average

