optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 5
  anneal_steps: [30000, 40000, 50000]
  anneal_rate: 0.3
step:
  total_step: 200
  log_step: 10
  synth_step: 100
  val_step: 100
  save_step: 100
