seed_everything: 42

model:
  class_path: lightning.systems.XvecFitSystem
  init_args:
    model:
      class_path: lightning.model.XvecTDNN
      init_args:
        p_dropout: 0.5

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 5e-4

lr_scheduler:
  class_path: torch.optim.lr_scheduler.OneCycleLR
  init_args:
    max_lr: 2e-3
    cycle_momentum: False
    div_factor: 5
    final_div_factor: 1e+3
    pct_start: 0.15

data:
  class_path: lightning.datamodules.XvecDataModule
  init_args:
    preprocess_config:
      path:
        df_path: "./preprocessed_data/VCTK-speaker-info.csv"
        preprocessed_path: "./preprocessed_data/VCTK/all"
    train_config:
      optimizer:
        batch_size: 64
    split: accent

trainer:
  ### Train settings
  max_epochs: 200
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1

  ### Logging and saving settings
  enable_checkpointing: True
  default_root_dir: output/xvec

  ### GPU-related settings
  accelerator: gpu
  devices: [0]
  strategy: ddp
  auto_select_gpus: True

  ### Callbacks
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        log_momentum: True

  ### Malicious settings
  profiler: simple

  ### Depreciated settings
  # deterministic: True
