name: meta-tune
type: meta-tune

_phn_emb_config:
  embedding: &embedding
    type: embedding
    refresh: False
  codebook: &codebook
    type: codebook
    size: 100
    representation_dim: 1024
    attention:
      type: soft-m
      share: False

adapt:
  type: lang # spk/lang
  class: MAML # MAML/iMAML
  speaker_emb: dvec # shared/table/encoder
  phoneme_emb: *codebook  # *embedding/*codebook
  imaml:
    K: 5  # CG steps  # TODO: need tuning
    reg_param: 1  # TODO: need tuning
    batch_size: 5
    stochastic: True

  modules:
    - encoder
    - variance_adaptor
    - decoder
    - mel_linear
    - postnet

  task: &task
    ways: 1
    shots: 64
    queries: 16
    lr: 0.001

  train:
    << : *task
    steps: 5
    meta_batch_size: 1

  test:
    << : *task
    batch_size: 16
    shots: 64
    queries: 16
    steps: 20000 # max adaptation steps for testing
