name: adamwmaml
type: meta  # meta/baseline/imaml, get_system

_phn_emb_config:
  embedding: &embedding
    type: embedding
    refresh: False

adapt:
  type: spk # spk/lang
  #class: AdamWMAML # MAML/iMAML, not used
  speaker_emb: table # shared/table/encoder
  phoneme_emb: *embedding  # *embedding/*codebook
  modules:
    - speaker_emb
    - variance_adaptor
    - decoder
    - mel_linear
    - postnet

  task: &task
    ways: 1
    shots: 5
    queries: 5
    lr: &lr 0.01

  learner_config:
    class_path: lightning.algorithms.MAML.AdamWMAML
    init_args:
      lr: *lr
      weight_decay: 0.01
      clip_grad_norm: 1.0
      adapt_inner_lr: True

  train:
    << : *task
    steps: 2
    meta_batch_size: 4

  test:
    << : *task
    queries: 1
    steps: 100 # max adaptation steps for testing
    saving_steps: [5, 10, 20, 50, 100, 200, 400, 600, 800, 1000]
    avg_train_spk_emb: False
    1-shot: False
